server:
  port: 8082
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/job_post_api
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true